---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: Install apache webserver
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family']|lower == 'redhat'

    - name: start apache service
      service:
        name: httpd
        state: started
      when: ansible_facts['os_family']|lower == 'redhat'

    - name: Install apache webserver
      yum:
        name: apache2
        state: present
      when: ansible_facts['os_family']|lower == 'debian'

    - name: start apache service
      service:
        name: apache2
        state: started
      when: ansible_facts['os_family']|lower == 'debian'

    - name: Copy index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0755