---

- name: Extract tomcat archive name
  shell: echo "{{ tomcat_url }}" | awk -F/ '{print $NF}'
  register: tomcat_archive

- name: Install Java
  yum: 
    name: java-1.8.0-openjdk
    state: present

- name: Add tomcat group
  group: 
    name: tomcat

- name: Add tomcat user
  user: 
    name: tomcat
    group: tomcat
    home: /home/tomcat
    createhome: no
    system: yes

- name: Create a tomcat home directory
  file: 
    path: /home/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Download tomcat
  get_url:
    url: "{{ tomcat_url }}"
    dest: "/tmp/{{ tomcat_archive.stdout_lines[0] }}"

- name: Extract tomcat archive
  unarchive: 
    src: "/tmp/{{ tomcat_archive.stdout_lines[0] }}"
    dest: /home/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /home/tomcat/bin

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat service
  service: 
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd" 
