---
- name: Install apache webserver
  yum:
    name: apache2
    state: present

- name: Create index file
  template:
    src: index.html.j2
    dest: "{{ doc_root }}/index.html"
    owner: root
    group: root
    mode: 0755
  vars:
    env: Prod
    os: "{{ ansible_os_family }}"
    host: "{{ansible_hostname }}"
  notify:
    - Restart apache2

- name: start apache service
  service:
    name: apache2
    state: started

