---
# tasks file for apache

- name: Install Apache webserver on Redhat
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install Apache webserver on Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
