---
# tasks file for tomcat

- name: Install tomcat on RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install tomcat on Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
